-- Full Backup
BACKUP DATABASE DBS_ASSIGNMENT
TO DISK = 'C:\Temp\DBS_ASSIGNMENT_FullBackup.bak'
	WITH INIT,
	NAME = 'DBS_ASSIGNMENT_FullBackup';
GO

-- Differential Backup
BACKUP DATABASE DBS_ASSIGNMENT
TO DISK = 'C:\Temp\DBS_ASSIGNMENT_Differential.bak'
	WITH DIFFERENTIAL,
	NAME = 'DBS_ASSIGNMENT_Differential';
GO

-- Transaction Log
BACKUP LOG DBS_ASSIGNMENT
TO DISK = 'C:\Temp\DBS_ASSIGNMENT.log'
	WITH CHECKSUM,
	NAME = 'DBS_ASSIGNMENT_Log';
GO


-- Restore Full backup
RESTORE DATABASE DBS_ASSIGNMENT
FROM DISK = 'C:\Temp\DBS_ASSIGNMENT_FullBackup.bak'
WITH NORECOVERY

-- Restore Differential backup
RESTORE
DATABASE DBS_ASSIGNMENT
FROM DISK = 'C:\Temp\DBS_ASSIGNMENT_Differential.bak'
WITH NORECOVERY

-- Restore Transaction Log
RESTORE LOG DBS_ASSIGNMENT
FROM DISK = 'C:\Temp\DBS_ASSIGNMENT.log'